language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=quick_email --omit='*/quick_email/__init__.py','*/quick_email/sender.py' -m unittest discover tests
after_script:
  - coveralls
