language: python
sudo: required
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - coverage run --source=quick_email -m unittest discover tests
after_script:
  - coveralls
